swagger: "2.0"
info:
  description: "SENDGRID PIXAERA'S MICROSERVICE"
  version: "1.0.0"
  title: "SENDGRID MICROSERVICE"
  contact:
    email: "luizgustavoahsc@gmail.com"
host: "localhost:3000"
basePath: "/"
schemes:
  - "http"
paths:
  /send_email:
    post:
      tags:
        - "Email"
      summary: "SUMMARY OF REQUEST"
      description: "DESCRIPTION OF REQUEST"
      operationId: "SendEmail"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "User e-mail and Email template number."
          required: true
          schema:
            $ref: "#/definitions/SendEmail"
        - in: "header"
          name: "Authorization"
          type: "string"
          description: "Authorization Token to identify requester"
          required: true
      responses:
        200:
          description: "Successful"
        400:
          description: "Empty e-mail or email_template_key"
        401:
          description: "Incorrect e-mail or email_template_key"
        500:
          description: "Unknown error"
        503:
          description: "Lost connection with database"
securityDefinitions:
  ApiKey:
    type: "apiKey"
    in: "header"
    name: "Authorization"
definitions:
  SendEmail:
    type: "object"
    properties:
      user_email:
        type: "string"
      email_template_key:
        type: "string"